### ISSUE TITLE
tests don't run

### ISSUE THREAD

**Issue by agarwal** [janestreet/pa_ounit#4]
```
$ cat tests.ml 
open Core.Std
TEST "foo" = String.length "foo" = 2

$ ocamlfind ocamlopt -o tests -linkall -linkpkg -package core,pa_ounit.syntax -syntax camlp4o -thread tests.ml

$ ./tests inline-test-runner -verbose
(* no output *)
```

What am I doing wrong?

**Comment by ghost** [comment]
You need to pass a library name. Try:

```
$ ./tests inline-test-runner dummy -verbose
```

You can set a library name when compiling test with `-pa-ounit-lib`. This is explained in the [readme](https://github.com/janestreet/pa_ounit#building-and-running-the-tests).

**Comment by agarwal** [comment]
Thanks. I didn't know how to pass -pa-ounit-lib as instructed. For others' benefit, the full invocation required is:

```
ocamlfind ocamlopt -o tests -linkall -linkpkg -package core,pa_ounit.syntax -syntax camlp4o -thread -ppopt -pa-ounit-lib -ppopt foo tests.ml
```

BTW, I guess this library is deprecated. Is there an alternative ppx based project that is supposed to supersede this?

**Comment by bmillwood** [comment]
The ppx version of this library is not released yet. Next public release (after 113.00.00) will probably be a little slow to arrive, since it'll involve some adjustments to our tooling, and maybe new packages, but it's on the way.

(closing because it sounds like you have a resolution you're happy with, but feel free to re-open if there's still something that needs doing.)

**Comment by agarwal** [comment]
Thanks. Issue is resolved.
